package com.ticketing.system.Core.Domain.users;

import java.util.Collection;
import java.util.ArrayList;
import java.util.List;

import com.ticketing.system.Core.Application.interfaces.IPasswordHasher;
import com.ticketing.system.Core.Domain.company.CompanyAppointment;
import com.ticketing.system.Core.Domain.shared.InvariantChecked;

public class User implements InvariantChecked {

    private MemberProfile memberProfile;
    private List<ManagementInvitation> managementInvitations;
    private int userId;
    private String username;
    private String email;
    private String password;
    private List<CompanyAppointment> companyAppointments;

    public User(int userId, String username, String email, String password) {
        this.userId = userId;
        this.username = username;
        this.email = email;
        this.password = password;
        this.managementInvitations = new ArrayList<>();
        this.memberProfile = new MemberProfile();
        this.companyAppointments = new ArrayList<>();
        // Messaging is its own aggregate now (Conversation / IConversationRepository in
        // messaging/);
        // User no longer holds an inbox field.
    }

    public CompanyAppointment acceptInvitation(int companyId) {
        CompanyAppointment appointment = getAppointmentForCompany(companyId);
        if (appointment == null) {
            throw new RuntimeException("Cannot accept invitation: no appointment found for the specified company");
        }
        appointment.accept();
        return appointment;
    }

    public void rejectInvitation(int companyId) {
        CompanyAppointment appointment = getAppointmentForCompany(companyId);
        if (appointment == null) {
            throw new RuntimeException("Cannot reject invitation: no appointment found for the specified company");
        }
        appointment.reject();
        ;
    }

    public void receiveManagerAppointment(int companyId, int ownerid, List<Permission> permissions) {
        if (getAppointmentForCompany(companyId) != null) {
            throw new RuntimeException("User already has an active or pending appointment in this company");
        }

        CompanyAppointment appointment = CompanyAppointment.ManagerAppointment(
                0, // appointmentId would be generated by the repository in a real implementation
                companyId,
                this.userId,
                ownerid,
                permissions);

        companyAppointments.add(appointment);
    }

    public void addFounderAppointment(int companyId) {
        if (getAppointmentForCompany(companyId) != null) {
            throw new RuntimeException("User already has an appointment in this company");
        }

        CompanyAppointment appointment = CompanyAppointment.FoundingAppointment(
                0, // appointmentId would be generated by the repository in a real implementation
                companyId,
                this.userId,
                this.userId);

        companyAppointments.add(appointment);
    }

    public void receiveOwnerAppointment(int companyId, int appointerId) {
        if (getAppointmentForCompany(companyId) != null) {
            throw new RuntimeException("User already has an active or pending appointment in this company");
        }

        CompanyAppointment appointment = CompanyAppointment.OwnerAppointment(
                0, // appointmentId would be generated by the repository in a real implementation
                companyId,
                this.userId,
                appointerId);

        companyAppointments.add(appointment);
    }

    public void revokeManagerAppointment(int companyId) {
        CompanyAppointment appointment = getAppointmentForCompany(companyId);
        if (appointment == null) {
            throw new RuntimeException("Cannot remove appointment: no appointment found for the specified company");
        }
        appointment.revoke();
    }

    // Returns the User's appointment in the given company, or null if absent.
    public CompanyAppointment getAppointmentForCompany(int companyId) {
        for (CompanyAppointment appointment : companyAppointments) {
            if (appointment.getCompanyId() == companyId) {
                return appointment;
            }
        }
        return null;
    }

    // Helper for the "view my appointments" flow (UC-20) — returns only pending
    public List<CompanyAppointment> getActiveCompanyAppointments() {
        List<CompanyAppointment> activeAppointments = new ArrayList<>();
        for (CompanyAppointment appointment : companyAppointments) {
            if (appointment.getStatus() == AppointmentStatus.ACTIVE) {
                activeAppointments.add(appointment);
            }
        }
        return activeAppointments;
    }

    // returns all pending appointments, which includes both invitations (for
    // managers) and ownership appointments awaiting acceptance.
    public List<CompanyAppointment> getPendingCompanyAppointments() {
        List<CompanyAppointment> pendingAppointments = new ArrayList<>();
        for (CompanyAppointment appointment : companyAppointments) {
            if (appointment.getStatus() == AppointmentStatus.PENDING) {
                pendingAppointments.add(appointment);
            }
        }
        return pendingAppointments;
    }

    // Helper for permission-checking flows (UC-19/21/22/24).
    public boolean isOwnerInCompany(int companyId) {
        CompanyAppointment appointment = getAppointmentForCompany(companyId);
        return appointment != null
                && appointment.getRole() == CompanyRole.Owner
                && appointment.getStatus() == AppointmentStatus.ACTIVE;
    }

    public boolean hasPermissionInCompany(int companyId, Permission permission) {
        CompanyAppointment appointment = getAppointmentForCompany(companyId);
        if (appointment == null) {
            return false;
        }
        return appointment.hasPermission(permission);
    }

    public void setAsManager(int companyId) {
        memberProfile.setAsManager(companyId);
    }

    public List<ManagementInvitation> getManagementInvitations() {
        return this.managementInvitations;
    }

    public void ModifyManagerPermissions(int companyId, int targetId, List<Permission> newPermissions) {
        CompanyAppointment appointment = getAppointmentForCompany(companyId);
        if (appointment == null) {
            throw new RuntimeException("No appointment found for the specified company");
        }
        if (appointment.getRole() != CompanyRole.Owner || appointment.getStatus() != AppointmentStatus.ACTIVE) {
            throw new RuntimeException("Only active owners can modify manager permissions");
        }
        CompanyAppointment targetAppointment = null;
        for (CompanyAppointment app : companyAppointments) {
            if (app.getCompanyId() == companyId && app.getTargetId() == targetId) {
                targetAppointment = app;
                break;
            }
        }
        if (targetAppointment == null) {
            throw new RuntimeException("Target user does not have an appointment in this company");
        }
        if (targetAppointment.getRole() != CompanyRole.Manager
                || targetAppointment.getStatus() != AppointmentStatus.ACTIVE) {
            throw new RuntimeException("Target appointment must be an active manager appointment");
        }
        targetAppointment.setPermissions(EnumSet.copyOf(newPermissions));
    }

    // ---------------------------------------------------------------------------
    // Skeleton additions — accessors + secure password change.
    // ---------------------------------------------------------------------------

    public int getUserId() {
        return userId;
    }

    public String getUsername() {
        return username;
    }

    /** Email registered at sign-up. Used for uniqueness checks. UC-11. */
    public String getEmail() {
        return email;
    }

    /**
     * Verifies a candidate raw password against the stored hash. UC-12.
     *
     * <p>
     * The hash never leaves this entity — the hasher does the comparison
     * in place. The {@link IPasswordHasher} collaborator is passed in rather
     * than held as a field so the entity stays a pure domain object.
     */
    public boolean verifyPassword(String rawPassword, IPasswordHasher hasher) {
        return hasher.matches(rawPassword, this.password);
    }

    public MemberProfile getMemberProfile() {
        return memberProfile;
    }

    public List<CompanyAppointment> getAllCompanyAppointments() {
        return companyAppointments;
    }

    // UC-11 / future profile-edit — domain receives already-hashed password (per
    // lecture 2).
    public void changePassword(String newHashedPassword) {
        throw new UnsupportedOperationException("UC-11: not implemented");
    }

    @Override
    public void checkInvariants() {
        if (userId <= 0) {
            throw new IllegalStateException("User invariant violated: userId must be positive (was " + userId + ")");
        }
        if (username == null || username.isBlank()) {
            throw new IllegalStateException("User invariant violated: username must be non-blank");
        }
        if (email == null || email.isBlank()) {
            throw new IllegalStateException("User invariant violated: email must be non-blank");
        }
        if (password == null || password.isBlank()) {
            throw new IllegalStateException("User invariant violated: password hash must be non-blank");
        }
        if (managementInvitations == null) {
            throw new IllegalStateException("User invariant violated: managementInvitations list must not be null");
        }
        if (companyAppointments == null) {
            throw new IllegalStateException("User invariant violated: companyAppointments list must not be null");
        }
    }
}
