package com.ticketing.system.Core.Domain.users;

import java.util.EnumSet;
import java.util.ArrayList;
import java.util.List;

import com.ticketing.system.Core.Application.interfaces.IPasswordHasher;
import com.ticketing.system.Core.Domain.shared.InvariantChecked;

public class User implements InvariantChecked {

    private int userId;
    private String username;
    private String email;
    private String password;
    private List<CompanyAppointment> companyAppointments;

    public User(int userId, String username, String email, String password) {
        this.userId = userId;
        this.username = username;
        this.email = email;
        this.password = password;
        this.companyAppointments = new ArrayList<>();
        // Messaging is its own aggregate now (Conversation / IConversationRepository in
        // messaging/);
        // User no longer holds an inbox field.
    }

    public CompanyAppointment acceptInvitation(int companyId) {
        CompanyAppointment appointment = getPendingCompanyAppointments(companyId);
        if (appointment == null) {
            throw new RuntimeException("Cannot accept invitation: no appointment found for the specified company");
        }
        CompanyAppointment activeAppointment = getActiveCompanyAppointments(companyId);
        if (activeAppointment != null) {
            companyAppointments.remove(activeAppointment);
        }
        appointment.accept();
        return appointment;
    }

    public void rejectInvitation(int companyId) {
        CompanyAppointment appointment = getPendingCompanyAppointments(companyId);
        if (appointment == null) {
            throw new RuntimeException("Cannot reject invitation: no appointment found for the specified company");
        }
        appointment.reject();
        ;
    }

    public void receiveManagerAppointment(int companyId, int ownerid, List<Permission> permissions) {
        if (getActiveCompanyAppointments(companyId) != null || getPendingCompanyAppointments(companyId) != null) {
            throw new RuntimeException("User already has an active or pending appointment in this company");
        }

        CompanyAppointment appointment = CompanyAppointment.ManagerAppointment(
                0, // appointmentId would be generated by the repository in a real implementation
                companyId,
                this.userId,
                ownerid,
                permissions);

        companyAppointments.add(appointment);
    }

    public void addFounderAppointment(int companyId) {
        if (getActiveCompanyAppointments(companyId) != null || getPendingCompanyAppointments(companyId) != null) {
            throw new RuntimeException("User already has an active or pending appointment in this company");
        }

        CompanyAppointment appointment = CompanyAppointment.FoundingAppointment(
                0, // appointmentId would be generated by the repository in a real implementation
                companyId,
                this.userId,
                this.userId);

        companyAppointments.add(appointment);
    }

    // add new pending owner appointment to target user. Will throw if target user
    // already has an active or pending appointment in the company.
    // note that the user cant call this method on themselves, only the appointer
    // can call it on the target user, and the appointer must have permission to
    // appoint (be an active owner or have APPOINT_MANAGER permission).
    public void receiveOwnerAppointment(int companyId, int appointerId) {
        if (getPendingCompanyAppointments(companyId) != null) {
            throw new RuntimeException("User already has an pending appointment in this company");
        }
        CompanyAppointment activeAppointment = getActiveCompanyAppointments(companyId);
        if (activeAppointment != null && activeAppointment.getRole() == CompanyRole.Owner) {
            throw new RuntimeException("User already has an active appointment in this company");
        }

        CompanyAppointment appointment = CompanyAppointment.OwnerAppointment(
                0, // appointmentId would be generated by the repository in a real implementation
                companyId,
                this.userId,
                appointerId);

        companyAppointments.add(appointment);
    }

    public void revokeAppointment(int companyId, int revokerId) {
        CompanyAppointment appointment = getActiveCompanyAppointments(companyId);
        if (appointment == null) {
            throw new RuntimeException("Cannot remove appointment: no appointment found for the specified company");
        }
        appointment.revoke(revokerId);
    }

    // Returns the User's appointment in the given company, or null if absent.
    public List<CompanyAppointment> getAppointmentForCompany(int companyId) {
        List<CompanyAppointment> appointments = new ArrayList<>();
        for (CompanyAppointment appointment : companyAppointments) {
            if (appointment.getCompanyId() == companyId) {
                appointments.add(appointment);
            }
        }
        return appointments.isEmpty() ? null : appointments;
    }

    // Helper for the "view my appointments" flow (UC-20) — returns only pending
    public CompanyAppointment getActiveCompanyAppointments(int companyId) {
        for (CompanyAppointment appointment : companyAppointments) {
            if (appointment.getCompanyId() == companyId && appointment.getStatus() == AppointmentStatus.ACTIVE) {
                return appointment;
            }
        }
        return null;
    }

    // returns all pending appointments, which includes both invitations (for
    // managers) and ownership appointments awaiting acceptance.
    public CompanyAppointment getPendingCompanyAppointments(int companyId) {
        for (CompanyAppointment appointment : companyAppointments) {
            if (appointment.getCompanyId() == companyId && appointment.getStatus() == AppointmentStatus.PENDING) {
                return appointment;
            }
        }
        return null;
    }

    // Helper for permission-checking flows (UC-19/21/22/24).
    public boolean isOwnerInCompany(int companyId) {
        CompanyAppointment appointment = getActiveCompanyAppointments(companyId);
        return appointment != null && appointment.getRole() == CompanyRole.Owner;
    }

    // Will throw if the user is not an active owner in the company. Used to secure
    public void requireOwnerInCompany(int companyId) {
        if (!isOwnerInCompany(companyId)) {
            throw new RuntimeException("User is not an owner in this company");
        }
    }

    /**
     * Will throw if the user doesn't have the specified permission in the company.
     * Used to secure flows that require specific permissions.
     */
    public void requirePermissionInCompany(int companyId, Permission permission) {
        if (!hasPermissionInCompany(companyId, permission)) {
            throw new RuntimeException("Missing permission: " + permission);
        }
    }

    public boolean hasPermissionInCompany(int companyId, Permission permission) {
        CompanyAppointment appointment = getActiveCompanyAppointments(companyId);
        if (appointment == null) {
            return false;
        }
        return appointment.hasPermission(permission);
    }

    public void ModifyManagerPermissions(int companyId, int inviterId, List<Permission> newPermissions) {
        CompanyAppointment appointment = getActiveCompanyAppointments(companyId);
        if (appointment == null) {
            throw new RuntimeException("No appointment found for the specified company");
        }
        if (appointment.getInviterId() != inviterId) {// only the original appointer can modify permissions
            throw new RuntimeException("Only the original appointer can modify manager permissions");
        } // only Owners can be inviter, so there's no need to check inviter's permissions
          // separately
        if (appointment.getRole() != CompanyRole.Manager) {
            throw new RuntimeException("Can only modify permissions for manager appointments");
        }

        appointment.setPermissions(EnumSet.copyOf(newPermissions));
    }

    // ---------------------------------------------------------------------------
    // Skeleton additions — accessors + secure password change.
    // ---------------------------------------------------------------------------

    public int getUserId() {
        return userId;
    }

    public String getUsername() {
        return username;
    }

    /** Email registered at sign-up. Used for uniqueness checks. UC-11. */
    public String getEmail() {
        return email;
    }

    /**
     * Verifies a candidate raw password against the stored hash. UC-12.
     *
     * <p>
     * The hash never leaves this entity — the hasher does the comparison
     * in place. The {@link IPasswordHasher} collaborator is passed in rather
     * than held as a field so the entity stays a pure domain object.
     */
    public boolean verifyPassword(String rawPassword, IPasswordHasher hasher) {
        return hasher.matches(rawPassword, this.password);
    }

    public List<CompanyAppointment> getAllCompanyAppointments() {
        return companyAppointments;
    }

    // UC-11 / future profile-edit — domain receives already-hashed password (per
    // lecture 2).
    public void changePassword(String newHashedPassword) {
        throw new UnsupportedOperationException("UC-11: not implemented");
    }

    @Override
    public void checkInvariants() {
        if (userId <= 0) {
            throw new IllegalStateException("User invariant violated: userId must be positive (was " + userId + ")");
        }
        if (username == null || username.isBlank()) {
            throw new IllegalStateException("User invariant violated: username must be non-blank");
        }
        if (email == null || email.isBlank()) {
            throw new IllegalStateException("User invariant violated: email must be non-blank");
        }
        if (password == null || password.isBlank()) {
            throw new IllegalStateException("User invariant violated: password hash must be non-blank");
        }
        if (companyAppointments == null) {
            throw new IllegalStateException("User invariant violated: companyAppointments list must not be null");
        }
    }
}
